### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by benjaminpjones** [benjaminpjones/govariants#11]
We should have one!

**Comment by benjaminpjones** [comment]
[Samtaegeuk](https://en.wikipedia.org/wiki/Taegeuk#Tricolored_taegeuk) but with Vue greens and OGS white.  I chose this because the Samtaegeuk is a variant of the Taiji which looks like a variant of the OGS logo.

![Samtaegeuk but with Vue greens and OGS white](https://user-images.githubusercontent.com/25233703/187350291-62943ca4-aab9-4cc9-ba53-bd5ea9b3c61f.svg)

BTW if anyone has ideas for a different or modified logo, we can discuss!  I went ahead and put this in because we needed some replacement for the placeholder Vue icon.

**Comment by GreenAsJade** [comment]
I came here to submit a logo just like that one, except not as good.    

The only thing I do wonder is whether the black deserves to be actual black, which would be a better link with heritage and topic.

**Comment by benjaminpjones** [comment]
I didn't realize you were watching these! 😄

> The only thing I do wonder is whether the black deserves to be actual black, which would be a better link with heritage and topic.

Actually an earlier iteration did just use OGS black & white, but I switched to Vue colors because it fit better with the site's current color scheme.  I never tried a black white and green combo though - maybe it would work?

<img width="333" alt="Screen Shot 2022-09-04 at 8 06 19 PM" src="https://user-images.githubusercontent.com/25233703/188353390-303b39bb-a2a8-43a2-a5f7-21838683704e.png">

**Comment by GreenAsJade** [comment]
Yeah I think there's a reasonable chance that there's a green that will work.   (The red somehow sticks out too much - I imagine that's what you concluded.    :) )

**Comment by JonKo314** [comment]
Vue's color scheme is nice, but I think we should be able to come up with something of our own.

> The only thing I do wonder is whether the black deserves to be actual black, which would be a better link with heritage and topic.

I think so too, but then the third color shouldn't be red I think, because black, white and red reminds me of Germany (and Austria) around 1940.

**Comment by GreenAsJade** [comment]
> I didn't realize you were watching these! 😄

Via comments in slack, rather than actively here :)

**Comment by benjaminpjones** [comment]
Oh huh somehow I missed this further discussion - haha @JonKo314 I couldn't put a finger on it, but there I did sense a certain *harshness* to that first iteration 😅

**Comment by JonKo314** [comment]
I've been thinking about colors a bit. I like the blackish, whitish logo, but all colors should be (somehow) distinguishable from the background when using dark and light mode. That's not easy with blackish and whitish in the logo, but I think it's manageable. Also it would be *nice to have*, if the logo worked as a stone on the brownish board.

![image](https://github.com/govariantsteam/govariants/assets/91629164/41d98a05-f2e5-463e-9d0f-1d3d377d47db)

![image](https://github.com/govariantsteam/govariants/assets/91629164/4004ce54-4f0d-43c6-ab60-770de59dc387)

**Comment by benjaminpjones** [comment]
I like it!

> I like the blackish, whitish logo, but all colors should be (somehow) distinguishable from the background when using dark and light mode.

We could use an outline if one background is proving particularly tricky.  I think OGS uses highlights to address this issue and also give the logo a bit of depth.

> Also it would be nice to have, if the logo worked as a stone on the brownish board.

Yeah!  Maybe for three-player games like parallel (n=3), maybe we can default to these!

https://github.com/govariantsteam/govariants/blob/1e76193943cac187d26951c66040c8ff41c5404d/packages/vue-client/src/components/boards/ParallelGoBoard.vue#L42-L45

```
const distinct_colors =
  props.config.num_players <= 3
    ? LOGO_COLORS
    : [...];
```

**Comment by JonKo314** [comment]
@benjaminpjones can you tell me something about the geometry? Is the boundary between green and white just a semicircle with a radius that is half as big as the radius of the whole logo? If so, I think that's enough information for me to construct the shape.

**Comment by benjaminpjones** [comment]
That's correct, all just semicircles, rotated by 120°!  But hopefully you don't have to recreate the geometry.. you could probably just patch the fill colors in the svg in my earlier comment.

```diff
- <path d="M-150 259.808A300 300 0 0 0 300 0a225 225 0 0 0-450 0z" fill="#cd2e3a"/>
+ <path d="M-150 259.808A300 300 0 0 0 300 0a225 225 0 0 0-450 0z" fill="#4ab04a"/>
- <path d="M-150-259.808a300 300 0 0 0 0 519.616A150 150 0 0 0 0 0z" fill="#010101"/>
+ <path d="M-150-259.808a300 300 0 0 0 0 519.616A150 150 0 0 0 0 0z" fill="#0e101b"/>
- <path d="M0 0a150 150 0 0 1 300 0 300 300 0 0 0-450-259.908A150 150 0 0 0 0 0z" fill="#dededd"/>
+ <path d="M0 0a150 150 0 0 1 300 0 300 300 0 0 0-450-259.908A150 150 0 0 0 0 0z" fill="#fbeeee"/>
```
